project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

website:
  title: "New coreR Book with awesome package"
  # subtitle: "Oct 21 - Oct 25" (only for book)
  # reader-mode: false

  favicon: cover.png # learning hub logo

sidebar:
  - title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
          href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
          href: https://twitter.com/ucsb_nceas
      - icon: github
          href: https://github.com/nceas-learning-hub/2024-test-coreR

    contents:
      - text: "Reprodicibility Activity"
        href: materials/s01_activity_reproducibility_lego.qmd  ###  (coreRlessons v0.1.0)
      - text: "Collaborating with GitHub"
        href: materials/s02_github_collaboration.qmd  ###  (coreRlessons v0.1.0)
      - text: "Intro to GitHub"
        href: materials/s03_github_introduction.qmd  ###  (coreRlessons v0.1.0)

    # - s09_lesson_with_slides.qmd ### test lesson



# bibliography: book.bib

format:
  html:
    theme: cosmo
    css: style.css
    # Note HD: latex rendering issues, maybe with column-margin
  # pdf:
  #   documentclass: scrreprt

